# Site settings

title: 'Effective code | Damian Pieczynski'
email: piecyk@gmail.com

description: > Orbit Developer at Capita Employee Benefits
Passion for creating great software, working in a very Agile focused way, practising Scrum, TDD, BDD etc. and any other
technology that helps me keep ahead of the game.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: piecu
github_username:  piecyk


# Build settings
markdown: kramdown
